functionsDirectory = "C:\\Users\\Noman Traders\\Desktop\\Watches Website\\watches-react-app\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\Noman Traders\\Desktop\\Watches Website\\watches-react-app\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\Noman Traders\\Desktop\\Watches Website\\watches-react-app\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]