functionsDirectory = "C:\\Users\\Noman Traders\\Desktop\\Watches Website\\watches-react-app\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\Noman Traders\\Desktop\\Watches Website\\watches-react-app\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\Noman Traders\\Desktop\\Watches Website\\watches-react-app\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[build]
  functions = "netlify/functions"
  publish = "dist"


[functions]

[functions."*"][build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
<<<<<<<< HEAD:watches-react-app/netlify.toml
========

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
>>>>>>>> 3698631 (Fix Vite config for Netlify):netlify.toml
